MachineIntelligenceCore:Visualization: mic::opengl::visualization::WindowMazeOfDigits Class Reference
mic::opengl::visualization::WindowMazeOfDigits Class Reference
OpenGL-based window responsible for displaying maze of digits (0-9) in a heat map-like form.
#include <WindowMazeOfDigits.hpp>
Public Member Functions
WindowMazeOfDigits (std::string name_="MazeOfDigits", unsigned int position_x_=0, unsigned int position_y_=0, unsigned int width_=512, unsigned int height_=512)
virtual ~WindowMazeOfDigits ()
void displayHandler (void)
void setMazePointer (mic::types::TensorXfPtr displayed_maze_)
void setPathPointer (std::shared_ptr< std::vector< mic::types::Position2D > > saccadic_path_)
Public Member Functions inherited from mic::opengl::visualization::Window
Window (std::string name_="OpenGlWindow", unsigned int position_x_=0, unsigned int position_y_=0, unsigned int width_=512, unsigned int height_=512)
virtual ~Window ()
unsigned int getId () const
std::string getName () const
virtual void mouseHandler (int button, int state, int x, int y)
virtual void reshapeHandler (int width_, int height_)
Public Member Functions inherited from mic::opengl::visualization::DrawingUtils
virtual ~DrawingUtils ()
void draw_frame (float x1, float y1, float x2, float y2, float r, float g, float b, float a)
void draw_grid (float r, float g, float b, float a, float cells_h, float cells_v, float line_width_=1.0)
void draw_mark (mark m, float x, float y, float size, float line_width, float r, float g, float b, float a)
void draw_circle (float x, float y, float size, float line_width, float r, float g, float b, float a)
void draw_plus (float x, float y, float size, float line_width, float r, float g, float b, float a)
void draw_cross (float x, float y, float size, float line_width, float r, float g, float b, float a)
void draw_square (float x, float y, float size, float line_width, float r, float g, float b, float a)
void draw_square_in_place (float size, float line_width, float r, float g, float b, float a)
void draw_filled_square (float x, float y, float size, float r, float g, float b, float a)
void draw_rectangle (float x, float y, float h, float w, float r, float g, float b, float a)
void draw_filled_rectangle (float x, float y, float h, float w, float r, float g, float b, float a)
void draw_texture_in_place (float size)
void draw_filled_square_in_place (float radius, float line_width, float r, float g, float b, float a)
void draw_filled_rectangle_in_place (float radius_x, float radius_y, float line_width, float r, float g, float b, float a)
void draw_cuboid (float radius, float line_width, float height, float r, float g, float b, float a)
void draw_text (float x, float y, char *string, float r, float g, float b, float a, void *font)
void draw_text_3i (float x, float y, float z, char *string, float r, float g, float b, float a, void *font)
void draw_cursor (float x, float y, float r, float g, float b, float a)
void draw_text_3d (GLfloat x, GLfloat y, char *text)
float to_radians (float degrees)
Private Attributes
mic::types::TensorXfPtr displayed_maze
std::shared_ptr< std::vector
< mic::types::Position2D > > saccadic_path
Saccadic path to be displayed - a sequence of consecutive agent positions.
Additional Inherited Members
Protected Member Functions inherited from mic::opengl::visualization::Window
void keyhandlerFullscreen (void)
Protected Attributes inherited from mic::opengl::visualization::Window
std::string name
unsigned int position_x
unsigned int position_y
unsigned int width
unsigned int height
unsigned int previous_width
unsigned int previous_height
unsigned int id
bool fullscreen_mode
Detailed Description
OpenGL-based window responsible for displaying maze of digits (0-9) in a heat map-like form.
Author
tkornuta
Definition at line 54 of file WindowMazeOfDigits.hpp.
Constructor & Destructor Documentation
mic::opengl::visualization::WindowMazeOfDigits::WindowMazeOfDigits (std::string name_ = "MazeOfDigits", unsigned int position_x_ = 0, unsigned int position_y_ = 0, unsigned int width_ = 512, unsigned int height_ = 512)
Constructor. NULLs the image pointer.
Definition at line 31 of file WindowMazeOfDigits.cpp.
References displayed_maze.
mic::opengl::visualization::WindowMazeOfDigits::~WindowMazeOfDigits () virtual
Destructor.
Definition at line 41 of file WindowMazeOfDigits.cpp.
Member Function Documentation
void mic::opengl::visualization::WindowMazeOfDigits::displayHandler (void) virtual
Refreshes the content of the window.
Implements mic::opengl::visualization::Window.
Definition at line 46 of file WindowMazeOfDigits.cpp.
References mic::opengl::visualization::Agent, mic::opengl::visualization::Digits, displayed_maze, mic::opengl::visualization::DrawingUtils::draw_circle(), mic::opengl::visualization::DrawingUtils::draw_cross(), mic::opengl::visualization::DrawingUtils::draw_filled_rectangle(), mic::opengl::visualization::DrawingUtils::draw_grid(), mic::opengl::visualization::Goals, saccadic_path, and mic::opengl::visualization::Walls.
void mic::opengl::visualization::WindowMazeOfDigits::setMazePointer (mic::types::TensorXfPtr displayed_maze_)
Sets pointer to displayed maze.
Definition at line 183 of file WindowMazeOfDigits.cpp.
References displayed_maze.
void mic::opengl::visualization::WindowMazeOfDigits::setPathPointer (std::shared_ptr< std::vector< mic::types::Position2D > > saccadic_path_)
Sets pointer to displayed digit.
Definition at line 191 of file WindowMazeOfDigits.cpp.
References saccadic_path.
Member Data Documentation
mic::types::TensorXfPtr mic::opengl::visualization::WindowMazeOfDigits::displayed_maze private
Pointer to displayed matrix.
Definition at line 89 of file WindowMazeOfDigits.hpp.
Referenced by displayHandler(), setMazePointer(), and WindowMazeOfDigits().
std::shared_ptr<std::vector <mic::types::Position2D> > mic::opengl::visualization::WindowMazeOfDigits::saccadic_path private
Saccadic path to be displayed - a sequence of consecutive agent positions.
Definition at line 92 of file WindowMazeOfDigits.hpp.
Referenced by displayHandler(), and setPathPointer().
The documentation for this class was generated from the following files:
src/opengl/visualization/WindowMazeOfDigits.hpp
src/opengl/visualization/WindowMazeOfDigits.cpp