MachineIntelligenceCore:Visualization: mic::opengl::application::OpenGLEpisodicApplication Class Reference
mic::opengl::application::OpenGLEpisodicApplication Class Reference abstract
Parent class for all applications basing on episodes, without distinguising learning and training phases. Each episode will end when step will return false.
#include <OpenGLEpisodicApplication.hpp>
Public Member Functions
OpenGLEpisodicApplication (std::string node_name_)
virtual ~OpenGLEpisodicApplication ()
virtual void processingThread (void)
Function realizing the processing thread. Implements basic quit/pause/single step functionality. In each step it calls the performSingleStep() method. Can be overridden by derived classes.
Public Member Functions inherited from mic::opengl::application::OpenGLApplication
OpenGLApplication (std::string node_name_)
virtual ~OpenGLApplication ()
virtual void initialize (int argc, char *argv[])=0
virtual void run ()
Protected Member Functions
virtual void startNewEpisode ()=0
virtual void finishCurrentEpisode ()=0
Protected Member Functions inherited from mic::opengl::application::OpenGLApplication
virtual void performInitialStep (void)
The initial step - empty, to be overridden.
virtual void performFinalStep (void)
The initial step - empty, to be overridden.
Protected Attributes
unsigned long episode
Episode counter.
mic::configuration::Property
< long > number_of_episodes
Detailed Description
Parent class for all applications basing on episodes, without distinguising learning and training phases. Each episode will end when step will return false.
Author
tkornuta
Date
Feb 19, 2016
Definition at line 39 of file OpenGLEpisodicApplication.hpp.
Constructor & Destructor Documentation
mic::opengl::application::OpenGLEpisodicApplication::OpenGLEpisodicApplication (std::string node_name_)
Default constructor. Sets the application/node name and registers properties.
Parameters
node_name_ Name of the application/node (in configuration file).
Definition at line 29 of file OpenGLEpisodicApplication.cpp.
References number_of_episodes.
virtual mic::opengl::application::OpenGLEpisodicApplication::~OpenGLEpisodicApplication () inline virtual
Default destructor - empty.
Definition at line 50 of file OpenGLEpisodicApplication.hpp.
Member Function Documentation
virtual void mic::opengl::application::OpenGLEpisodicApplication::finishCurrentEpisode () protected pure virtual
Method called when given episode ends (goal: export collected statistics to file etc.) - abstract, to be overridden.
Referenced by processingThread().
void mic::opengl::application::OpenGLEpisodicApplication::processingThread (void) virtual
Function realizing the processing thread. Implements basic quit/pause/single step functionality. In each step it calls the performSingleStep() method. Can be overridden by derived classes.
Author
tkornuta
Reimplemented from mic::opengl::application::OpenGLApplication.
Definition at line 39 of file OpenGLEpisodicApplication.cpp.
References episode, finishCurrentEpisode(), number_of_episodes, and startNewEpisode().
virtual void mic::opengl::application::OpenGLEpisodicApplication::startNewEpisode () protected pure virtual
Method called at the beginning of new episode (goal: to reset the statistics etc.) - abstract, to be overridden.
Referenced by processingThread().
Member Data Documentation
unsigned long mic::opengl::application::OpenGLEpisodicApplication::episode protected
Episode counter.
Definition at line 72 of file OpenGLEpisodicApplication.hpp.
Referenced by processingThread().
mic::configuration::Property<long> mic::opengl::application::OpenGLEpisodicApplication::number_of_episodes protected
Property: number of episodes, after which the application will end. 0 (default value) deactivates terminal condition (unlimited number of episodes).
Definition at line 77 of file OpenGLEpisodicApplication.hpp.
Referenced by OpenGLEpisodicApplication(), and processingThread().
The documentation for this class was generated from the following files:
src/opengl/application/OpenGLEpisodicApplication.hpp
src/opengl/application/OpenGLEpisodicApplication.cpp