MachineIntelligenceCore:Visualization: mic::opengl::visualization::WindowMNISTDigit Class Reference
mic::opengl::visualization::WindowMNISTDigit Class Reference
OpenGL-based window responsible for displaying a MNIST digit with a moving agent on top.
#include <WindowMNISTDigit.hpp>
Public Member Functions
WindowMNISTDigit (std::string name_="MNISTDigit", unsigned int position_x_=0, unsigned int position_y_=0, unsigned int width_=512, unsigned int height_=512)
virtual ~WindowMNISTDigit ()
void displayHandler (void)
void setDigitPointer (mic::types::TensorXfPtr displayed_digit_)
void setPathPointer (std::shared_ptr< std::vector< mic::types::Position2D > > saccadic_path_)
Public Member Functions inherited from mic::opengl::visualization::Window
Window (std::string name_="OpenGlWindow", unsigned int position_x_=0, unsigned int position_y_=0, unsigned int width_=512, unsigned int height_=512)
virtual ~Window ()
unsigned int getId () const
std::string getName () const
virtual void mouseHandler (int button, int state, int x, int y)
virtual void reshapeHandler (int width_, int height_)
Public Member Functions inherited from mic::opengl::visualization::DrawingUtils
virtual ~DrawingUtils ()
void draw_frame (float x1, float y1, float x2, float y2, float r, float g, float b, float a)
void draw_grid (float r, float g, float b, float a, float cells_h, float cells_v, float line_width_=1.0)
void draw_mark (mark m, float x, float y, float size, float line_width, float r, float g, float b, float a)
void draw_circle (float x, float y, float size, float line_width, float r, float g, float b, float a)
void draw_plus (float x, float y, float size, float line_width, float r, float g, float b, float a)
void draw_cross (float x, float y, float size, float line_width, float r, float g, float b, float a)
void draw_square (float x, float y, float size, float line_width, float r, float g, float b, float a)
void draw_square_in_place (float size, float line_width, float r, float g, float b, float a)
void draw_filled_square (float x, float y, float size, float r, float g, float b, float a)
void draw_rectangle (float x, float y, float h, float w, float r, float g, float b, float a)
void draw_filled_rectangle (float x, float y, float h, float w, float r, float g, float b, float a)
void draw_texture_in_place (float size)
void draw_filled_square_in_place (float radius, float line_width, float r, float g, float b, float a)
void draw_filled_rectangle_in_place (float radius_x, float radius_y, float line_width, float r, float g, float b, float a)
void draw_cuboid (float radius, float line_width, float height, float r, float g, float b, float a)
void draw_text (float x, float y, char *string, float r, float g, float b, float a, void *font)
void draw_text_3i (float x, float y, float z, char *string, float r, float g, float b, float a, void *font)
void draw_cursor (float x, float y, float r, float g, float b, float a)
void draw_text_3d (GLfloat x, GLfloat y, char *text)
float to_radians (float degrees)
Private Attributes
mic::types::TensorXfPtr displayed_digit
std::shared_ptr< std::vector
< mic::types::Position2D > > saccadic_path
Saccadic path to be displayed - a sequence of consecutive agent positions.
Additional Inherited Members
Protected Member Functions inherited from mic::opengl::visualization::Window
void keyhandlerFullscreen (void)
Protected Attributes inherited from mic::opengl::visualization::Window
std::string name
unsigned int position_x
unsigned int position_y
unsigned int width
unsigned int height
unsigned int previous_width
unsigned int previous_height
unsigned int id
bool fullscreen_mode
Detailed Description
OpenGL-based window responsible for displaying a MNIST digit with a moving agent on top.
Author
tkornuta
Definition at line 54 of file WindowMNISTDigit.hpp.
Constructor & Destructor Documentation
mic::opengl::visualization::WindowMNISTDigit::WindowMNISTDigit (std::string name_ = "MNISTDigit", unsigned int position_x_ = 0, unsigned int position_y_ = 0, unsigned int width_ = 512, unsigned int height_ = 512)
Constructor. NULLs the image pointer.
Definition at line 30 of file WindowMNISTDigit.cpp.
References displayed_digit.
mic::opengl::visualization::WindowMNISTDigit::~WindowMNISTDigit () virtual
Destructor.
Definition at line 40 of file WindowMNISTDigit.cpp.
Member Function Documentation
void mic::opengl::visualization::WindowMNISTDigit::displayHandler (void) virtual
Refreshes the content of the window.
Implements mic::opengl::visualization::Window.
Definition at line 45 of file WindowMNISTDigit.cpp.
References mic::opengl::visualization::Agent, displayed_digit, mic::opengl::visualization::DrawingUtils::draw_circle(), mic::opengl::visualization::DrawingUtils::draw_cross(), mic::opengl::visualization::DrawingUtils::draw_filled_rectangle(), mic::opengl::visualization::DrawingUtils::draw_grid(), mic::opengl::visualization::Goals, mic::opengl::visualization::Pixels, and saccadic_path.
void mic::opengl::visualization::WindowMNISTDigit::setDigitPointer (mic::types::TensorXfPtr displayed_digit_)
Sets pointer to displayed digit.
Definition at line 163 of file WindowMNISTDigit.cpp.
References displayed_digit.
void mic::opengl::visualization::WindowMNISTDigit::setPathPointer (std::shared_ptr< std::vector< mic::types::Position2D > > saccadic_path_)
Sets pointer to displayed digit.
Definition at line 171 of file WindowMNISTDigit.cpp.
References saccadic_path.
Member Data Documentation
mic::types::TensorXfPtr mic::opengl::visualization::WindowMNISTDigit::displayed_digit private
Pointer to displayed matrix.
Definition at line 89 of file WindowMNISTDigit.hpp.
Referenced by displayHandler(), setDigitPointer(), and WindowMNISTDigit().
std::shared_ptr<std::vector <mic::types::Position2D> > mic::opengl::visualization::WindowMNISTDigit::saccadic_path private
Saccadic path to be displayed - a sequence of consecutive agent positions.
Definition at line 92 of file WindowMNISTDigit.hpp.
Referenced by displayHandler(), and setPathPointer().
The documentation for this class was generated from the following files:
src/opengl/visualization/WindowMNISTDigit.hpp
src/opengl/visualization/WindowMNISTDigit.cpp