MachineIntelligenceCore:Visualization: mic::opengl::application::OpenGLTrainThenTestApplication Class Reference
mic::opengl::application::OpenGLTrainThenTestApplication Class Reference abstract
#include <OpenGLTrainThenTestApplication.hpp>
Public Member Functions
OpenGLTrainThenTestApplication (std::string node_name_)
virtual ~OpenGLTrainThenTestApplication ()
Public Member Functions inherited from mic::opengl::application::OpenGLApplication
OpenGLApplication (std::string node_name_)
virtual ~OpenGLApplication ()
virtual void initialize (int argc, char *argv[])=0
virtual void run ()
Protected Member Functions
virtual bool performSingleStep ()
virtual bool performLearningStep ()=0
virtual bool performTestingStep ()=0
Protected Member Functions inherited from mic::opengl::application::OpenGLApplication
virtual void processingThread (void)
Function realizing the processing thread. Implements basic quit/pause/single step functionality. In each step it calls the performSingleStep() method. Can be overridden by derived classes.
virtual void performInitialStep (void)
The initial step - empty, to be overridden.
virtual void performFinalStep (void)
The initial step - empty, to be overridden.
Detailed Description
Definition at line 32 of file OpenGLTrainThenTestApplication.hpp.
Constructor & Destructor Documentation
mic::opengl::application::OpenGLTrainThenTestApplication::OpenGLTrainThenTestApplication (std::string node_name_)
Default constructor. Sets the application/node name and registers properties.
Parameters
node_name_ Name of the application/node (in configuration file).
Definition at line 30 of file OpenGLTrainThenTestApplication.cpp.
virtual mic::opengl::application::OpenGLTrainThenTestApplication::~OpenGLTrainThenTestApplication () inline virtual
Default destructor - empty.
Definition at line 43 of file OpenGLTrainThenTestApplication.hpp.
Member Function Documentation
virtual bool mic::opengl::application::OpenGLTrainThenTestApplication::performLearningStep () protected pure virtual
Perform learning step - abstract, to be overridden.
Returns
Returns false when test learning is completed.
Referenced by performSingleStep().
bool mic::opengl::application::OpenGLTrainThenTestApplication::performSingleStep (void) protected virtual
Performs single step of computations. Depending on the state, calls learning or testing step - switches from learning to testing then learning return false.
Definition at line 36 of file OpenGLTrainThenTestApplication.cpp.
References performLearningStep(), and performTestingStep().
virtual bool mic::opengl::application::OpenGLTrainThenTestApplication::performTestingStep () protected pure virtual
Perform testing step - abstract, to be overridden.
Returns
Returns false when test learning is completed.
Referenced by performSingleStep().
The documentation for this class was generated from the following files:
src/opengl/application/OpenGLTrainThenTestApplication.hpp
src/opengl/application/OpenGLTrainThenTestApplication.cpp