MachineIntelligenceCore:Visualization: mic::opengl::application::OpenGLContinuousLearningApplication Class Reference
mic::opengl::application::OpenGLContinuousLearningApplication Class Reference abstract
#include <OpenGLContinuousLearningApplication.hpp>
Public Member Functions
OpenGLContinuousLearningApplication (std::string node_name_)
virtual ~OpenGLContinuousLearningApplication ()
Public Member Functions inherited from mic::opengl::application::OpenGLApplication
OpenGLApplication (std::string node_name_)
virtual ~OpenGLApplication ()
virtual void initialize (int argc, char *argv[])=0
virtual void run ()
Protected Member Functions
virtual bool performSingleStep (void)
Performs single step of computations - switches between learning and testing depending on the iteration number.
virtual bool performLearningStep ()=0
virtual bool performTestingStep ()
virtual void collectTestStatistics ()
virtual void populateTestStatistics ()
Protected Member Functions inherited from mic::opengl::application::OpenGLApplication
virtual void processingThread (void)
Function realizing the processing thread. Implements basic quit/pause/single step functionality. In each step it calls the performSingleStep() method. Can be overridden by derived classes.
virtual void performInitialStep (void)
The initial step - empty, to be overridden.
virtual void performFinalStep (void)
The initial step - empty, to be overridden.
Protected Attributes
mic::configuration::Property
< unsigned int > learning_iterations_to_test_ratio
Number of learning steps after which a single classification test will be performed.
mic::configuration::Property
< unsigned int > number_of_averaged_test_measures
Numbers of steps that will be averages.
unsigned long learning_iteration
Learning iteration counter - used in interlaces learning/testing mode.
Detailed Description
Definition at line 32 of file OpenGLContinuousLearningApplication.hpp.
Constructor & Destructor Documentation
mic::opengl::application::OpenGLContinuousLearningApplication::OpenGLContinuousLearningApplication (std::string node_name_)
Default constructor. Sets the application/node name and registers properties.
Parameters
node_name_ Name of the application/node (in configuration file).
Definition at line 29 of file OpenGLContinuousLearningApplication.cpp.
References learning_iteration, learning_iterations_to_test_ratio, and number_of_averaged_test_measures.
virtual mic::opengl::application::OpenGLContinuousLearningApplication::~OpenGLContinuousLearningApplication () inline virtual
Default destructor - empty.
Definition at line 44 of file OpenGLContinuousLearningApplication.hpp.
Member Function Documentation
virtual void mic::opengl::application::OpenGLContinuousLearningApplication::collectTestStatistics () inline protected virtual
Collects test statistics, executed in every testing step - virtual, empty now, to be overridden.
Definition at line 67 of file OpenGLContinuousLearningApplication.hpp.
Referenced by performTestingStep().
virtual bool mic::opengl::application::OpenGLContinuousLearningApplication::performLearningStep () protected pure virtual
Perform learning - abstract, to be overridden.
Referenced by performSingleStep().
bool mic::opengl::application::OpenGLContinuousLearningApplication::performSingleStep (void) protected virtual
Performs single step of computations - switches between learning and testing depending on the iteration number.
Definition at line 41 of file OpenGLContinuousLearningApplication.cpp.
References learning_iterations_to_test_ratio, performLearningStep(), and performTestingStep().
bool mic::opengl::application::OpenGLContinuousLearningApplication::performTestingStep () protected virtual
Testing is divided into two phases: collection of test statistics and their population. The former is executed in every testing step, whereas the latter only every number_of_averaged_test_measures testing steps.
Definition at line 53 of file OpenGLContinuousLearningApplication.cpp.
References collectTestStatistics(), learning_iteration, number_of_averaged_test_measures, and populateTestStatistics().
Referenced by performSingleStep().
virtual void mic::opengl::application::OpenGLContinuousLearningApplication::populateTestStatistics () inline protected virtual
Populates test statistics, executed only every number_of_averaged_test_measures testing steps - virtual, empty now, to be overridden.
Definition at line 72 of file OpenGLContinuousLearningApplication.hpp.
Referenced by performTestingStep().
Member Data Documentation
unsigned long mic::opengl::application::OpenGLContinuousLearningApplication::learning_iteration protected
Learning iteration counter - used in interlaces learning/testing mode.
Definition at line 81 of file OpenGLContinuousLearningApplication.hpp.
Referenced by OpenGLContinuousLearningApplication(), and performTestingStep().
mic::configuration::Property<unsigned int> mic::opengl::application::OpenGLContinuousLearningApplication::learning_iterations_to_test_ratio protected
Number of learning steps after which a single classification test will be performed.
Definition at line 72 of file OpenGLContinuousLearningApplication.hpp.
Referenced by OpenGLContinuousLearningApplication(), and performSingleStep().
mic::configuration::Property<unsigned int> mic::opengl::application::OpenGLContinuousLearningApplication::number_of_averaged_test_measures protected
Numbers of steps that will be averages.
Definition at line 78 of file OpenGLContinuousLearningApplication.hpp.
Referenced by OpenGLContinuousLearningApplication(), and performTestingStep().
The documentation for this class was generated from the following files:
src/opengl/application/OpenGLContinuousLearningApplication.hpp
src/opengl/application/OpenGLContinuousLearningApplication.cpp